# Generated by Django 3.2.8 on 2021-10-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0002_auto_20211020_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='name',
        ),
    ]
