# Generated by Django 3.2.8 on 2021-10-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=50)),
                ('prevent', models.JSONField()),
                ('image_url', models.ImageField(upload_to='images/')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.CharField(max_length=20)),
            ],
        ),
    ]
