# Generated by Django 3.2.8 on 2021-10-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0002_auto_20211021_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionmodel',
            name='medicine_image',
            field=models.ImageField(blank=True, upload_to='solution/'),
        ),
    ]
